meta_product_name: "Getbubo"
meta_title: "Great Software"
meta_description: "Relevant description"
meta_image: "cover.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
